# Generated by Django 4.2 on 2023-04-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_blogpost_author_blogpost_topics_topic_notify_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
